### ISSUE TITLE
Failed pip install

### ISSUE THREAD

**Issue by fredshone** [arfc/osier#55]
Failed pip install using latest python.

Details:

Windows (10)
`python -m pip install osier pyomo==6.4.1`

I tried:

Fixed by back-tracking to 3.10.

BUT please clarify expected supported python versions in installation instructions.

Suggest you also explicitly add version of python to CI.

**Comment by victoraalves** [comment]
I have the same issue.

**Comment by samgdotson** [comment]
Thanks for opening this issue @fredshone and confirming the problem @victoraalves. I think this issue is related to #50 and #59. Pyomo appears to be incompatible with NumPy 2.0, at the moment. https://github.com/Pyomo/pyomo/issues/3290
